---
- name: Configure FreeIPA client
  hosts: ipa_clients
  become: yes
  vars:
    ipa_server: ipa.otus.lan
    ipa_domain: otus.lan
    ipa_realm: OTUS.LAN
    ipa_admin: admin
    ipa_admin_password: otus2022  # Замените на реальный пароль

  tasks:
    - name: Install required packages
      yum:
        name:
          - vim
          - chrony
          - freeipa-client
          - oddjob-mkhomedir
        state: present
        update_cache: yes

    - name: Set timezone to Europe/Moscow
      timezone:
        name: Europe/Moscow

    - name: Configure and enable chronyd
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Disable SELinux permanently
      selinux:
        state: disabled

    - name: Disable SELinux immediately
      command: setenforce 0

    - name: Configure hosts file
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.57.10 ipa.otus.lan ipa
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

    - name: Configure Kerberos client
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 0644

    - name: Join client to FreeIPA domain
      command: |
        ipa-client-install \
          --domain={{ ipa_domain }} \
          --realm={{ ipa_realm }} \
          --server={{ ipa_server }} \
          --principal={{ ipa_admin }} \
          --password="{{ ipa_admin_password }}" \
          --mkhomedir \
          --no-ntp \
          --unattended
      register: ipa_join
      changed_when: "'Client configuration complete' in ipa_join.stdout"

    - name: Enable SSSD
      service:
        name: sssd
        state: started
        enabled: yes
